# NNFS Chapter 2 - Coding Our First Neurons

* [Single neuron with 3 inputs example](https://nnfs.io/bkr/)
* [A single neuron with 4 inputs](https://nnfs.io/djp/)
* [3 neuron layer with 4 inputs example](https://nnfs.io/mxo/)

In [2]:
def compute_output(inputs, weights, bias):
    output = (
            inputs[0] * weights[0] +
            inputs[1] * weights[1] +
            inputs[2] * weights[2] + bias
    )
    return output

compute_output(
    inputs=[0, 1, 2],
    weights=[0.1, 0.2, 0.3],
    bias=2
)

2.8

In [4]:
def compute_output2(inputs, weights, bias):
    output = (
            inputs[0] * weights[0] +
            inputs[1] * weights[1] +
            inputs[2] * weights[2] +
            inputs[3] * weights[3] + bias
    )
    return output

compute_output2(
    inputs=[0, 1, 2, 3],
    weights=[0.1, 0.2, 0.3, 1.0],
    bias=3
)

6.8

In [11]:
def layer_with_three_neurons_and_four_inputs(inputs, weights, biases):
    weights1, weights2, weights3 = weights
    bias1, bias2, bias3 = biases

    outputs = [
        # Neuron 1:
        inputs[0]*weights1[0] +
        inputs[1]*weights1[1] +
        inputs[2]*weights1[2] +
        inputs[3]*weights1[3] + bias1,

        # Neuron 2:
        inputs[0]*weights2[0] +
        inputs[1]*weights2[1] +
        inputs[2]*weights2[2] +
        inputs[3]*weights2[3] + bias2,

        # Neuron 3:
        inputs[0]*weights3[0] +
        inputs[1]*weights3[1] +
        inputs[2]*weights3[2] +
        inputs[3]*weights3[3] + bias3
    ]

    return outputs

layer_with_three_neurons_and_four_inputs(
    inputs = [1, 2, 3, 2.5],
    weights = [
        [0.2, 0.8, -0.5, 1],
        [0.5, -0.91, 0.26, -0.5],
        [-0.26, -0.27, 0.17, 0.87]
    ],
    biases = [2, 3, 0.5]
)

[4.8, 1.21, 2.385]

In [12]:
def layer_with_neurons(inputs, weights, biases):
    layer_outputs = []

    for neuron_weights, neuron_bias in zip(weights, biases):
        neuron_output = 0

        for n_input, weight in zip(inputs, neuron_weights):
            neuron_output += n_input * weight

        neuron_output += neuron_bias
        layer_outputs.append(neuron_output)

    return layer_outputs


layer_with_neurons(
    inputs = [1, 2, 3, 2.5],
    weights = [
        [0.2, 0.8, -0.5, 1],
        [0.5, -0.91, 0.26, -0.5],
        [-0.26, -0.27, 0.17, 0.87]
    ],
    biases = [2, 3, 0.5]
)

[4.8, 1.21, 2.385]

# Dot product and vector addition
* [Math behind the dot product](https://nnfs.io/xpo)

In [2]:
a = [1, 2, 3]
b = [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
dot_product

20

## A single Neuron with numpy

In [3]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias
outputs

4.8

## A layer of Neurons with numpy

In [4]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases
layer_outputs

array([4.8  , 1.21 , 2.385])

## A batch of inputs

In [13]:
inputs = [
    [1, 2, 3, 2.5],
    [2, 5, -1, 2],
    [-1.5, 2.7, 3.3, -0.8]
]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
]
biases = [2.0, 3.0, 0.5]

inputs = np.array(inputs).T
weights = np.array(weights)

layer_outputs = np.dot(weights, inputs) + biases
layer_outputs

array([[ 4.8  ,  9.9  , -0.09 ],
       [ 0.21 , -1.81 , -1.449],
       [ 3.885,  2.7  ,  0.026]])

# We will try something different now

Before, we were modeling neuron output using a single sample of data, a vector, so we wanted the output to be neuron specific.
Now we are modeling layer behavior on a batch of data. It’s more useful to have a list of outputs per sample than a list of neurons outputs.
In other words, we want the result to be related to the samples rather than related to the  neurons.

**the next layer expects a batch of inputs**

also important: **NumPy will convert the input list to numpy matrices internally.**

In [18]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
]
biases = [2.0, 3.0, 0.5]

np.dot(
    inputs,
    np.array(weights).T
) + biases

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [19]:
def layer_with_np(inputs=[], weights=[], biases=[]):
    layer_ouputs = np.dot(inputs, np.array(weights).T)
    return layer_ouputs + biases

layer_with_np(
    inputs = [
        [1.0, 2.0, 3.0, 2.5],
        [2.0, 5.0, -1.0, 2.0],
        [-1.5, 2.7, 3.3, -0.8]
    ],
    weights = [
        [0.2, 0.8, -0.5, 1.0],
        [0.5, -0.91, 0.26, -0.5],
        [-0.26, -0.27, 0.17, 0.87],
    ],
    biases = [2.0, 3.0, 0.5]
)

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])